name: Build and Package Python App

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller

      - name: Build executable
        run: |
          pyinstaller deed_virtual_drive_ui.py --onedir --windowed --hidden-import "PySide6.QtXml" --hidden-import "PySide6.QtUiTools" --add-data rsrc:rsrc --add-data ui:ui --add-data style:style --name "deed virtual drive" --contents-directory . --noconfirm

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build-artifacts
          path: dist
